import { lazy } from "react";

export const mainRoutes = [
  {
    path: "/",
    name: "Home",
    exact: true,
    component: lazy(() => import("../pages/HomePage")),
    isPrivate: false,
    isAdmin: false,
    restricted: false,
  },
  {
    path: "/product/:id",
    name: "Product",
    exact: true,
    component: lazy(() => import("../pages/ProductPage")),
    isPrivate: false,
    isAdmin: false,
    restricted: false,
  },
  {
    path: "/register",
    name: "Sign up",
    exact: true,
    component: lazy(() => import("../pages/RegistrationPage")),
    isPrivate: false,
    isAdmin: false,
    restricted: true,
  },
  {
    path: "/signin",
    name: "Sign in",
    exact: true,
    component: lazy(() => import("../pages/LoginPage")),
    isPrivate: false,
    isAdmin: false,
    restricted: true,
  },
  {
    path: "/cart",
    name: "Cart",
    exact: true,
    component: lazy(() => import("../pages/CartPage")),
    isPrivate: false,
    isAdmin: false,
    restricted: false,
  },
  {
    path: "/myorders",
    name: "My Orders",
    exact: true,
    component: lazy(() => import("../pages/OrderPage")),
    isPrivate: true,
    isAdmin: false,
    restricted: false,
  },
  {
    path: "/orders",
    name: "All Orders",
    exact: true,
    component: lazy(() => import("../pages/AdminOrdersPage")),
    isPrivate: true,
    isAdmin: true,
    restricted: false,
  },
  {
    path: "/order/:id",
    name: "Order Details",
    exact: true,
    component: lazy(() => import("../pages/AdminOrdersPageDetails")),
    isPrivate: true,
    isAdmin: true,
    restricted: false,
  },
  {
    path: "/ordersucces",
    name: "Order Success",
    exact: true,
    component: lazy(() => import("../pages/OrderSuccessPage")),
    isPrivate: true,
    isAdmin: false,
    restricted: false,
  },
];
